apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- exclude-l2-config.yaml
- namespace.yaml
- ./controllers
- ./crd
- ./rbac
- ./webhook
namespace: metallb-system
images:
- name: quay.io/metallb/controller
  newTag: v0.13.10
- name: quay.io/metallb/speaker
  newTag: v0.13.10
